# https://taskfile.dev
version: 3

vars:
  dir: ./bin/
  app_name_windows: gomovie_svr.exe
  app_name_unix: gomovie_svr
  parser_name_windows: gomovie_parser.exe
  parser_name_unix: gomovie_parser
  server_file: ./cmd/gomovie/gomovie.go
  parser_file: ./cmd/parse/parse_cli.go

tasks:
  default:
    desc: Default task which will be run if no target is specified
    aliases:
      - all
    cmds:
      - task: clean
      - task: setup
      - task: tidy
      - task: mod
      - task: test
      - task: build_all

  setup:
    desc: Sets up required directories etc.
    cmds:
      - cmd: mkdir {{.dir}}
        platforms: [darwin, linux]
      - cmd: powershell mkdir {{.dir}}
        platforms: [ windows ]

  build:
    desc: Builds the application
    deps: [clean]
    cmds:
      - cmd: go build -v -o {{.dir}}{{.app_name_windows}} {{.server_file}}
        platforms: [windows]
      - cmd: go build -v -o {{.dir}}{{.app_name_unix}} {{.server_file}}
        platforms: [darwin, linux]

  build_parser:
        desc: Builds the application
        deps: [clean]
        cmds:
          - cmd: go build -v -o {{.dir}}{{.parser_name_windows}} {{.parser_file}}
            platforms: [windows]
          - cmd: go build -v -o {{.dir}}{{.parser_name_unix}} {{.parser_file}}
            platforms: [darwin, linux]

  build_all:
        desc: Builds the application
        deps: [clean]
        cmds:
          - cmd: go build -v -o {{.dir}}{{.parser_name_windows}} {{.parser_file}}
            platforms: [windows]
          - cmd: go build -v -o {{.dir}}{{.app_name_windows}} {{.server_file}}
            platforms: [windows]
          - cmd: go build -v -o {{.dir}}{{.parser_name_unix}} {{.parser_file}}
            platforms: [darwin, linux]
          - cmd: go build -v -o {{.dir}}{{.app_name_unix}} {{.server_file}}
            platforms: [darwin, linux]

  test:
    desc: Runs tests for the application
    cmds:
      - go test -v ./...

  tidy:
    cmds:
      - go mod tidy

  mod:
    cmds:
      - go mod download

  clean:
    desc: Cleans up previously build binaries
    cmds:
      - cmd: rm -rf {{.dir}}*
        platforms: [darwin, linux]
      - cmd: powershell -File ./scripts/clean.ps1
        platforms: [windows]
